# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"

# Autoformat shell script source code
brew "shfmt"

# Cross-shell prompt for astronauts
brew "starship"

# UNIX shell (command interpreter)
brew "zsh"
