import = ["/Users/zachharris/.config/alacritty/font.toml", "/Users/zachharris/.config/alacritty/cursor.toml", "/Users/zachharris/.config/alacritty/window.toml", "/Users/zachharris/.config/alacritty/bell.toml", "/Users/zachharris/.config/alacritty/colors.toml", "/Users/zachharris/.config/alacritty/bindings.toml", "/Users/zachharris/.config/alacritty/debug.toml"]
live_config_reload = true
working_directory = "None"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = false



[scrolling]
history = 20000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["--login"]
program = "/bin/zsh"
