# Distributed revision control system
brew "git"

# Syntax-highlighting pager for git and diff output
brew "git-delta"

# Git extension for versioning large files
brew "git-lfs"

# Add GitHub support to git on the command-line
brew "hub"
