add_newline = true

[aws]
symbol = " "
format = "on [$symbol$profile]($style) "
disabled = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
disabled = true

[conda]
symbol = " "
disabled = true

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[⁊](bold red)"

[dart]
symbol = " "
disabled = true

[docker_context]
symbol = " "
disabled = false

[elixir]
symbol = " "

[elm]
disabled = true

[gcloud]
symbol = " "
format = "on [$symbol$account]($style) "
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = "ஃ "

[line_break]
disabled = false

[memory_usage]
symbol = " "

[nim]
symbol = " "
disabled = true

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[openstack]
disabled = true

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[status]
disabled = true

[swift]
symbol = "ﯣ "
